/* Generated By:JavaCC: Do not edit this line. ZigZagConstants.java */
package org.meandre.zigzag.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZigZagConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMA = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int LP = 9;
  /** RegularExpression Id. */
  int RP = 10;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int AT = 14;
  /** RegularExpression Id. */
  int LB = 15;
  /** RegularExpression Id. */
  int RB = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int EXCL = 18;
  /** RegularExpression Id. */
  int IMPORT = 19;
  /** RegularExpression Id. */
  int FROM = 20;
  /** RegularExpression Id. */
  int ALIAS = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int AUTO = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int SYMBOL = 25;
  /** RegularExpression Id. */
  int URI = 26;
  /** RegularExpression Id. */
  int VALUE = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"!\"",
    "\"import\"",
    "\"from\"",
    "\"alias\"",
    "\"as\"",
    "\"AUTO\"",
    "<NUMBER>",
    "<SYMBOL>",
    "<URI>",
    "<VALUE>",
  };

}
