/* Generated By:JavaCC: Do not edit this line. ZigZagConstants.java */
package org.meandre.zigzag.parser;

public interface ZigZagConstants {

  int EOF = 0;
  int COMA = 7;
  int EQUAL = 8;
  int LP = 9;
  int RP = 10;
  int DOT = 11;
  int COLON = 12;
  int SEMICOLON = 13;
  int AT = 14;
  int IMPORT = 15;
  int FROM = 16;
  int ALIAS = 17;
  int AS = 18;
  int SYMBOL = 19;
  int URI = 20;
  int VALUE = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"@\"",
    "\"import\"",
    "\"from\"",
    "\"alias\"",
    "\"as\"",
    "<SYMBOL>",
    "<URI>",
    "<VALUE>",
  };

}
