/* Generated By:JavaCC: Do not edit this line. ZigZagConstants.java */
package org.meandre.zigzag.parser;

public interface ZigZagConstants {

  int EOF = 0;
  int COMA = 7;
  int EQUAL = 8;
  int LP = 9;
  int RP = 10;
  int DOT = 11;
  int COLON = 12;
  int SEMICOLON = 13;
  int AT = 14;
  int LB = 15;
  int RB = 16;
  int PLUS = 17;
  int EXCL = 18;
  int IMPORT = 19;
  int FROM = 20;
  int ALIAS = 21;
  int AS = 22;
  int AUTO = 23;
  int NUMBER = 24;
  int SYMBOL = 25;
  int URI = 26;
  int VALUE = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"!\"",
    "\"import\"",
    "\"from\"",
    "\"alias\"",
    "\"as\"",
    "\"AUTO\"",
    "<NUMBER>",
    "<SYMBOL>",
    "<URI>",
    "<VALUE>",
  };

}
